### ISSUE TITLE
Type conversion error when running MONITOR command

### ISSUE THREAD

**Issue by dmb2168** [GhostPack/Rubeus#14] opened 2018-11-29 14:10 UTC
When running the monitor command with the following parameters in Cobalt Strike:

`execute-assembly /tmp/rubeus.exe monitor /interval: 5`

The monitoring function works (as determined by the tool outputting the various 4624 events that are occurring, but instead of dumping the TGT information along with the hash, we get the following error:

`[x] Value was either too large or too small for a UInt32`

I took a loot through the associated code for Marvest and noted that the `luid` value was being converted to a UInt32. Without knowing **why** this could be an issue, I change instances of uint32 to uint64 for Monitor as well as associated Harvest functions, recompiled and I got no more errors! I haven't submitted a PR because, well, I'm not sure if what I did is fixing the root cause error or if I am just bumbling around.

Also... my "fix" rendered the tool able to print out some information that it previously did not (Target luid, and Target service), it returns that it was able to Extract 0 tickets.. I'm not sure if this is related to my "fix" or some other thing..

**Comment by dmb2168** [comment] 2018-11-29 22:32
Added details: the server Rubeus was run on was Server 2012 R2
Domain functional level: Windows 2012 R2

**Comment by dmb2168** [comment] 2018-11-30 02:11
Another update, on this particular system Logon IDs are being returned as 9-digit hex strings (36 bits, rather than 32 bits)! Apparently Logon IDs are 64 bit?

**Comment by NickSanzotta** [comment] 2018-12-12 19:20
@dmb2168 I've experienced the same error `Value was either too large or too small for a UInt32`, would you be willing to share your solution?

**Comment by HarmJ0y** [comment] 2019-02-06 01:49
This unfortunately isn't as easy to fix as I hoped. There's a lot of code that uses only the UInt32 low part of a constructed LUID, so it's not as simple as fixing the lines in the Monitor4624 function. I'm looking at a few options.

**Comment by HarmJ0y** [comment] 2019-02-06 22:31
This should hopefully be fixed with https://github.com/GhostPack/Rubeus/commit/26a08457a36ab311e2590b4c366efe0f7669c1fd - if the issue isn't resolved, feel free to open the issue back up.

P.S. @BlueSkeye I revamped the Interop.LUID structure (including centralizing the string conversion code there) and restructured code to use the LUID structure instead of UInt32s.

**Closed by HarmJ0y** 2019-02-06 22:31 UTC
